name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-javascript:
    name: JavaScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5

      - name: Print time
        run: date

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          milliseconds: 2000

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.time }}"

      - name: Check that the reported PID is still running
        run: |
          PID=${{ steps.test-action.outputs.child_pid }}
          echo "Checking if PID $PID is running"
          if ps -p $PID > /dev/null
          then
              echo "Process $PID is running"
          else
              echo "Process $PID is not running"
              exit 1
          fi

      - name: Print time again
        run: date

      - name: Check if sleeping process is still running
        run: |
          if pgrep -x "sleep" > /dev/null
          then
              echo "Sleep process is still running"
          else
              echo "Sleep process is not running"
          fi

      - name: Wait for 70 seconds to see if background process keeps running
        run: sleep 70
      - name: Check again if sleeping process is still running
        run: |
          if pgrep -x "sleep" > /dev/null
          then
              echo "Sleep process is still running"
          else
              echo "Sleep process is not running"
          fi
